name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Install the latest version of uv and set the python version
        uses: astral-sh/setup-uv@v9.0.0
        with:
          python-version: "3.12"
      - name: Lint
        run: |
          uv run ruff format --check
          uv run ruff check
      - name: Test with python 3.12
        run: uv run --frozen pytest
